# .github/workflows/package-and-publish-deb.yml
name: Package & Publish .deb via FPM

on:
  push:
    tags:
      - 'v*'              # run on tag pushes, e.g. v2.1.4

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: toxiproxy
      # CLOUDSMITH_* secrets as before
      DISTRO: ubuntu
      RELEASE: focal

    steps:
      - uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Derive version from tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}        # e.g. "v2.1.4"
          echo "VERSION=${TAG#v}" >> $GITHUB_ENV   # strip leading "v"
          echo "Derived version: $VERSION"

      - name: Install FPM & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-dev build-essential fakeroot dpkg-dev
          sudo gem install --no-document fpm

      - name: Package with FPM
        run: |
          fpm -f -s dir -t deb \
            -n "${{ env.PACKAGE_NAME }}" \
            -v "${{ env.VERSION }}" \
            --architecture amd64 \
            --prefix /usr/local/bin \
            dist/toxiproxy-server \
            dist/toxiproxy-cli

      - name: Push to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key:  ${{ secrets.CLOUDSMITH_API_KEY }}
          command:  push
          format:   deb
          owner:    ${{ secrets.CLOUDSMITH_OWNER }}
          repo:     ${{ secrets.CLOUDSMITH_REPO }}
          distro:   ${{ env.DISTRO }}
          release:  ${{ env.RELEASE }}
          file:     "toxiproxy_${{ env.VERSION }}_amd64.deb"

