# .github/workflows/fetch-and-publish-deb.yml
name: Fetch & Publish Toxiproxy .deb

on:
  push:
    tags:
      - 'v*'       # runs whenever you push a tag like v2.12.1

jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      CLOUDSMITH_OWNER:   ${{ secrets.CLOUDSMITH_OWNER }}
      CLOUDSMITH_REPO:    ${{ secrets.CLOUDSMITH_REPO }}
      DISTRO:             ubuntu
      RELEASE:            focal

    steps:
      - name: Checkout (fetch tags)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0        # ensure we have the tag refs

      - name: Derive VERSION & TAG
        run: |
          # GITHUB_REF is refs/tags/vX.Y.Z
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "TAG=$TAG"       >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Will package version $VERSION from tag $TAG"

      - name: Download .deb from GitHub Releases
        run: |
          wget -qO toxiproxy_${VERSION}.deb \
            https://github.com/Shopify/toxiproxy/releases/download/${TAG}/toxiproxy_${VERSION}_amd64.deb

      - name: Verify download
        run: ls -lh toxiproxy_${VERSION}.deb

      - name: Push to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key:  ${{ env.CLOUDSMITH_API_KEY }}
          command:  push
          format:   deb
          owner:    ${{ env.CLOUDSMITH_OWNER }}
          repo:     ${{ env.CLOUDSMITH_REPO }}
          distro:   ${{ env.DISTRO }}
          release:  ${{ env.RELEASE }}
          file:     toxiproxy_${{ env.VERSION }}_amd64.deb

