# .github/workflows/fetch-and-publish-deb.yml
name: Fetch &  Publish Toxiproxy debian package

# Manually run this workflow and enter the version you want to fetch
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Toxiproxy version (e.g. 2.1.4)'
        required: true
        default: '2.1.4'

jobs:
  fetch-and-publish:
    runs-on: ubuntu-latest
    env:
      # These must be set in Settings → Secrets
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      CLOUDSMITH_OWNER:   ${{ secrets.CLOUDSMITH_OWNER }}
      CLOUDSMITH_REPO:    ${{ secrets.CLOUDSMITH_REPO }}
      DISTRO:             ubuntu
      RELEASE:            focal

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set VERSION & TAG
        run: |
          VERSION=${{ github.event.inputs.version }}
          TAG=v${VERSION}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=$TAG"         >> $GITHUB_ENV

      - name: Download the .deb from GitHub Releases
        run: |
          wget -qO toxiproxy_${{ env.VERSION }}.deb \
            https://github.com/Shopify/toxiproxy/releases/download/${{ env.TAG }}/toxiproxy_${{ env.VERSION }}_linux_amd64.deb

      - name: Verify download
        run: ls -lh toxiproxy_${{ env.VERSION }}.deb

      - name: Push to Cloudsmith
        uses: cloudsmith-io/action@master
        with:
          api-key:  ${{ env.CLOUDSMITH_API_KEY }}
          command:  push
          format:   deb
          owner:    ${{ env.CLOUDSMITH_OWNER }}
          repo:     ${{ env.CLOUDSMITH_REPO }}
          distro:   ${{ env.DISTRO }}
          release:  ${{ env.RELEASE }}
          file:     toxiproxy_${{ env.VERSION }}_amd64.deb
          republish: 'true'

